[ERROR] 2019-09-28 16:17:54,631 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:17:54,654 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:18:54,820 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:18:54,823 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:19:54,981 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:19:54,983 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:20:55,160 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:20:55,162 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:21:55,318 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:21:55,320 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:22:55,497 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:22:55,499 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:23:55,671 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:23:55,673 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:24:55,822 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:24:55,824 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:25:55,983 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:25:55,985 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:26:56,147 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:26:56,149 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:27:56,313 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:27:56,315 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:28:56,483 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:28:56,485 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:29:56,669 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:29:56,671 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:30:56,852 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:30:56,854 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:31:57,010 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:31:57,012 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:32:57,183 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:32:57,185 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:33:57,362 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:33:57,364 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:34:57,543 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:34:57,546 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:35:57,703 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:35:57,706 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:36:57,870 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:36:57,872 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:37:58,024 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:37:58,026 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:38:58,195 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:38:58,198 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:39:58,354 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:39:58,356 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:40:58,527 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:40:58,529 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:41:58,687 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:41:58,689 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:42:58,865 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:42:58,867 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:43:59,037 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:43:59,039 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:44:59,218 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:44:59,220 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:45:59,402 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:45:59,404 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:46:31,606 | /home/umoms/moms-bench/apps/frappe/frappe/app.py:
Site: moms-site1
Request Error
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/app.py", line 58, in application
    init_request(request)
  File "/home/umoms/moms-bench/apps/frappe/frappe/app.py", line 120, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/umoms/moms-bench/apps/frappe/frappe/auth.py", line 42, in __init__
    self.set_lang()
  File "/home/umoms/moms-bench/apps/frappe/frappe/auth.py", line 86, in set_lang
    frappe.local.lang = guess_language()
  File "/home/umoms/moms-bench/apps/frappe/frappe/translate.py", line 29, in guess_language
    lang_list = get_all_languages() or []
  File "/home/umoms/moms-bench/apps/frappe/frappe/translate.py", line 85, in get_all_languages
    return frappe.cache().get_value('languages', _get)
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 79, in get_value
    val = generator()
  File "/home/umoms/moms-bench/apps/frappe/frappe/translate.py", line 84, in _get
    return frappe.db.sql_list('select name from tabLanguage')
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 277, in sql_list
    return [r[0] for r in self.sql(query, values, debug=debug)]
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")
[ERROR] 2019-09-28 16:46:31,742 | /home/umoms/moms-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2019-09-28 16:46:31.607379-192.168.2.201-336
[ERROR] 2019-09-28 16:46:31,969 | /home/umoms/moms-bench/apps/frappe/frappe/app.py:
Site: moms-site1
Request Error
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/app.py", line 58, in application
    init_request(request)
  File "/home/umoms/moms-bench/apps/frappe/frappe/app.py", line 120, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/umoms/moms-bench/apps/frappe/frappe/auth.py", line 42, in __init__
    self.set_lang()
  File "/home/umoms/moms-bench/apps/frappe/frappe/auth.py", line 86, in set_lang
    frappe.local.lang = guess_language()
  File "/home/umoms/moms-bench/apps/frappe/frappe/translate.py", line 29, in guess_language
    lang_list = get_all_languages() or []
  File "/home/umoms/moms-bench/apps/frappe/frappe/translate.py", line 85, in get_all_languages
    return frappe.cache().get_value('languages', _get)
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 79, in get_value
    val = generator()
  File "/home/umoms/moms-bench/apps/frappe/frappe/translate.py", line 84, in _get
    return frappe.db.sql_list('select name from tabLanguage')
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 277, in sql_list
    return [r[0] for r in self.sql(query, values, debug=debug)]
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")
[ERROR] 2019-09-28 16:46:32,093 | /home/umoms/moms-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2019-09-28 16:46:31.970226-192.168.2.201-ced
[ERROR] 2019-09-28 16:46:59,578 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:46:59,579 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:47:59,735 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:47:59,737 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site2
Exception in Enqueue Events for Site moms-site2
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

[ERROR] 2019-09-28 16:48:59,902 | /home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py:
Site: moms-site1
Exception in Enqueue Events for Site moms-site1
Traceback (most recent call last):
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 93, in enqueue_events_for_site
    if is_scheduler_disabled():
  File "/home/umoms/moms-bench/apps/frappe/frappe/utils/scheduler.py", line 237, in is_scheduler_disabled
    return not frappe.utils.cint(frappe.db.get_single_value("System Settings", "enable_scheduler"))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 642, in get_single_value
    tabSingles where doctype=%s and field=%s""", (doctype, fieldname))
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/umoms/moms-bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/umoms/moms-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
OperationalError: (2003, "Can't connect to MySQL server on u'localhost' ([Errno 111] Connection refused)")

